MERGE INTO dim_symbol AS tgt
USING (
    SELECT SYMBOL, NAME, EXCHANGE
    FROM US_STOCK_DAILY.DCCM.Symbols
) AS src
ON tgt.SYMBOL = src.SYMBOL

WHEN MATCHED THEN UPDATE SET
    tgt.NAME     = src.NAME,
    tgt.EXCHANGE = src.EXCHANGE,
    tgt.LOAD_TS  = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (SYMBOL, NAME, EXCHANGE, LOAD_TS)
VALUES (src.SYMBOL, src.NAME, src.EXCHANGE, CURRENT_TIMESTAMP());

MERGE INTO AIRFLOW0928.DEV.dim_date_team3 AS tgt
USING (
    SELECT DISTINCT
        TRY_TO_DATE(DATE) AS FULL_DATE,
        YEAR(TRY_TO_DATE(DATE)) AS YEAR,
        QUARTER(TRY_TO_DATE(DATE)) AS QUARTER,
        MONTH(TRY_TO_DATE(DATE)) AS MONTH,
        DAY(TRY_TO_DATE(DATE)) AS DAY,
        DAYOFWEEK(TRY_TO_DATE(DATE)) AS DAY_OF_WEEK,
        WEEKOFYEAR(TRY_TO_DATE(DATE)) AS WEEK_OF_YEAR,
        TO_VARCHAR(TO_DATE(DATE), 'MMMM') AS MONTH_NAME,
        TO_VARCHAR(TO_DATE(DATE), 'DY') AS DAY_NAME
    FROM US_STOCK_DAILY.DCCM.Stock_History
    WHERE TRY_TO_DATE(DATE) IS NOT NULL
) AS src
ON tgt.FULL_DATE = src.FULL_DATE

WHEN MATCHED THEN UPDATE SET
    tgt.LOAD_TS = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    FULL_DATE, YEAR, QUARTER, MONTH, DAY, DAY_OF_WEEK, WEEK_OF_YEAR,
    MONTH_NAME, DAY_NAME, LOAD_TS
)
VALUES (
    src.FULL_DATE, src.YEAR, src.QUARTER, src.MONTH, src.DAY,
    src.DAY_OF_WEEK, src.WEEK_OF_YEAR, src.MONTH_NAME, src.DAY_NAME, CURRENT_TIMESTAMP()
);